name: dependabot-auto-merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    if: >
      github.actor == 'dependabot[bot]' &&
      !contains(github.event.pull_request.title, 'major')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge after CI
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
